version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # 써드파티 Actions만 pin
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-major"]