# .github/workflows/pr-check.yml
name: PR Type Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  type-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.7
        
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.1.0
        with:
          node-version: '22.13.0'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@fe1a63c94f9b5b83dc0a45228ac5a9ab52f6e83f # v4.0.0
        with:
          version: '10.15.1'
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Debug - 환경 확인
        run: |
          echo "Node.js: $(node --version)"
          echo "pnpm: $(pnpm --version)"
          echo "작업 디렉토리: $(pwd)"
          echo "패키지 목록:"
          pnpm list -r --depth=0
          
      - name: Build workspace packages
        run: |
          echo "=== 워크스페이스 패키지들 빌드 ==="
          # carousel 패키지 빌드 (타입 선언 파일 생성)
          pnpm --filter @watcha/carousel build
          
      - name: Run type check
        run: pnpm type-check
        
      - name: Run lint
        run: pnpm lint